#!/usr/bin/env python

import time, Queue
import electrum
q = Queue.Queue()

interface = electrum.Interface('ecdsa.net:110:s', q)
interface.start()
i, r = q.get()
if not interface.is_connected():
    raise BaseException("not connected")
# 2. get list of peers
interface.pipe.send("2\n")#end_request(2)#{'id':0, 'method':2, 'params':['1JHaKMpEB7LsZWjbHJZbzCVLndEG5G5UwZ']})
i, r = q.get(timeout=10000)
print r
