#!/usr/bin/env python

import util
peers = util.get_peers()
results = util.send_request(peers, {'method':'blockchain.address.get_history','params':['1ELzQwxokGTXQ7FSNFoFkWpV3ZTVPsrmDd']})

for n,v in results.items():
    print "%40s"%n, v



